name: C++ CI

on: [push, pull_request]

jobs:
  build:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ ubuntu-18.04, ubuntu-latest ]
          compiler: [ g++, clang++ ]
      name: ${{ matrix.compiler }} on ${{ matrix.os }}
      steps:
        - uses: actions/checkout@master
        - run: |
            sudo bash scripts/install.sh --no-build
            sh scripts/build.sh
            sh scripts/tests.sh
